---
title: "Discussion 12"
author: "Peter Lombardo"
date: "April 19, 2018"
output: html_document
---

#Ebay.com

1.	Perform a Scenario Design analysis as described below.  Consider whether it makes sense for your selected recommender system to perform scenario design twice, once for the organization (e.g. Amazon.com) and once for the organization's customers.

  a.	Who are your target users?
    i.	Target users are individuals who wish to buy and sell products in a secure online environment.
  b.	What are their key goals?
    i.	Their key goals are to either purchase or sell an item securely. 
  c.	How can you help them accomplish their goals?
    i.	eBay offers a medium in which a user can search for a desired product, both new and used, or sell a product they no longer want. They ensure secure            transactions, and protection against fraudulent sales and purchase. 
    
2.	Attempt to reverse engineer what you can about the site, from the site interface and any available information that you can find on the Internet or elsewhere.
  a.	From the front page of eBay.com it is clear they use a recommender system. I am a frequent user of eBay and my front page has items listed that meet my        personal interests and purchase. For example, I collect Football, Hockey, and Baseball memorabilia. My first page shows listing for jerseys, autographs,        trading cards, and various apparel.
  
3.	Include specific recommendations about how to improve the site's recommendation capabilities going forward. 
  a.	Often eBay will recommend and item I’ve viewed and decided not to purchase.  It would be better to list those last on my recommendation list as I am           clearly not interested in that particular item. 
